name: abctechfront
description: Fiap MBA project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Dev
  dartz: ^0.10.0-nullsafety.2
  json_annotation: ^4.0.1
  freezed_annotation: ^2.2.0
  rxdart: ^0.26.0
  dio: ^4.0.6
  wakelock: ^0.6.2
  intl: ^0.17.0

  #DI
  provider: ^6.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3

  #State
  shared_preferences: ^2.0.15

  #Bloc
  flutter_bloc: ^8.1.1

  #Ui
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.23
  flutter_conditional_rendering: ^2.0.0
  uuid: ^3.0.6
  multi_select_flutter: ^4.1.2
  geolocator: ^9.0.2

dev_dependencies:
  #Test
  flutter_test:
    sdk: flutter
  analyzer: ^4.7.0

  #Dev
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  build_runner: ^2.3.0
  lint: ^1.10.0

  #DI
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true
